### ISSUE TITLE
夜间模式问题

### ISSUE THREAD

**Issue by 5mdld** [kaCVanime/AnkiEnJa#4]
你好，日语卡组在iOS上夜间模式无法显示例句，一片白
另外左上角的词频和标签框与单词位置冲突，会重叠在一起

**Comment by kaCVanime** [comment]
已修复。ankiweb更新后需要24小时才能看到，可以先网盘下载导入试试。
https://pan.baidu.com/s/1zlu-nHg3hhtyoB2KobyHmw?pwd=cwte 

导入anki的时候，注意
勾选`导入选项-更新`下的`合并笔记模板`
导入成功后重启anki

**Comment by 5mdld** [comment]
谢谢，测试了一下没有问题
